name: Build webOS IPK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install webOS CLI
        run: npm install -g @webos-tools/cli

      - name: Package App to IPK
        continue-on-error: true
        run: ares-package tv-app

      - name: Upload IPK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-iptv-app
          path: "*.ipk"
